schedule: "0 7 * * *"  # 7:00 AM daily
edition: 0

email:
  from: "The Burrow<mail@burrow.janiskrasemann.com>"
  to: "janis.krasemann@proton.me"
  test_to: "burrow-test@fleneifvio.resend.app"
  resend_api_key: "${RESEND_API_KEY}"

sources:
  - type: weather
    latitude: 52.104000
    longitude: 9.357130
    name: "Hameln"

  - type: readwise
    api_token: "${READWISE_API_TOKEN}"

  - type: hackernews

  - type: reddit
    subreddits:
      - ClaudeCode
      - ExperiencedDevs

  - type: nitter
    nitter_instance: "https://nitter.net"
    usernames:
      - bcherny
      - GeoffreyHuntley
      - WesBos

  - type: unsplash
    api_token: "${UNSPLASH_ACCESS_KEY}"
    query: "morning,nature,calm"

  - type: reddit
    subreddits:
      - de
      - EU5
      - Finanzen
      - DnD
